apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  namespace: SOME_INVALID_NAMESPACE_REPLACE_ME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  minReadySeconds: 30
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: spring-music
          image: docker.io/adamfowleruk/spring-music
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
