apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  namespace: SOME_INVALID_NAMESPACE_REPLACE_ME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  minReadySeconds: 30
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: spring-music
          image: docker.io/adamfowleruk/spring-music
          imagePullPolicy: Always
          lifecycle: # See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment.cloud.kubernetes
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          # readinessProbe:
          #   httpGet:
          #     port: 4000
          #     path: /actuator/health/readiness
          ports:
            - containerPort: 4000
          env:
          - name: PORT
            value: "4000"
          - name: SPRING_PROFILE
            value: "in-memory"
          #   value: "postgres-k8s"
          # - name: POSTGRES_HOST
          #   value: {{ .Release.Name }}-postgresql
          # - name: POSTGRES_PORT
          #   value: "{{ .Values.postgresql.service.port }}"
          # - name: POSTGRES_DATABASE
          #   value: {{ .Values.postgresql.postgresqlDatabase }}
          # - name: POSTGRES_USERNAME
          #   value: {{ .Values.postgresql.postgresqlUsername }}
          # - name: POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ .Release.Name }}-postgresql
          #       key: postgresql-password