apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-music"
  namespace: "default"
spec:
  type: "NodePort"
  selector:
    app: "spring-music"
  ports:
    - name: "http"
      port: 4000
      nodePort: 32000
      protocol: "TCP"
