apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  minReadySeconds: 30
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: spring-music
          image: docker.io/adamfowleruk/spring-music
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: docker-registry-adamfowler
