spring:
  jpa:
    generate-ddl: true

# From spring boot 2.3+, see: https://hackmd.io/@ryanjbaxter/spring-on-k8s-workshop#Handling-In-Flight-Requests
server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost/music"
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  profiles: mysql-k8s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}"
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  profiles: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost/music"
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
---
spring:
  profiles: postgres-k8s
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
